{{- range $name, $service := .Values.services }}
{{- if $service.database.enabled }}
{{- $global := $.Values.global }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  DB_URL: {{ include "databaseUrl" (dict "local" $service "global" $global) | b64enc }}
  DB_NAME: {{ $service.database.name | b64enc }}
  DB_USERNAME: {{ $service.database.username | b64enc }}
  DB_PASSWORD: {{ $service.database.password | b64enc }}
  DB_DRIVER_CLASS_NAME: {{ $global.database.driverClassName | b64enc }}
  JPA_GENERATION: {{ include "getOrDefault" (dict "local" $service "global" $global "path" (list "application" "jpa" "hibernate" "ddlAuto")) | b64enc }}
---
{{- end }}
{{- end }}