server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: ${JPA_GENERATION}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 60000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 2000ms
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    topics:
      reserve-stock: ${KAFKA_TOPIC_RESERVE_STOCK}
      book-delivery: ${KAFKA_TOPIC_BOOK_DELIVERY}
      payment: ${KAFKA_TOPIC_PAYMENT}
      inventory-compensate: ${KAFKA_TOPIC_INVENTORY_COMPENSATE}
      delivery-compensate: ${KAFKA_TOPIC_DELIVERY_COMPENSATE}
      order-results: ${KAFKA_TOPIC_ORDER_RESULTS}
    template:
      default-topic: ${spring.kafka.topics.order-results}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${KAFKA_GROUP_ID}
      properties:
        spring:
          json:
            type:
              mapping: event:com.denisenko.event.ResultEvent